### ISSUE TITLE
VCert CLI argument for CSR is silently ignored when value is invalid

### ISSUE THREAD

**Issue by tr1ck3r** [Venafi/vcert#134]
**PROBLEM SUMMARY**
VCert CLI argument for CSR is silently ignored when value is invalid

**STEPS TO REPRODUCE**
```
vcert enroll -u https://tpp.venafi.example -t hw4+yAeOUcjTLao167ptIA== -z VCert --cn test.venafi.example --csr test.req
```

**EXPECTED RESULTS**
An error message stating that the value of the `--csr` parameter must be "local", "service", or "file:<path-to-csr-file>".  If the correct syntax had been specified VCert would have correctly returned the following error message:

> The '--cn' parameter cannot be used with '--csr file:'

**ACTUAL RESULTS**
```
Enter key pass phrase:************
Verifying - Enter key pass phrase:************
vCert: 2019/12/11 07:49:44 Successfully connected to TPP
vCert: 2019/12/11 07:49:48 Successfully read zone configuration for VCert
vCert: 2019/12/11 07:49:49 Successfully created request for test.venafi.example
vCert: 2019/12/11 07:49:50 Successfully posted request for test.venafi.example, will pick up by \VED\Policy\VCert\test.venafi.example
vCert: 2019/12/11 07:49:50 Issuance of certificate is pending...
```
The `--csr` parameter was silently ignored and a certificate was enrolled using local CSR generation (the default behavior when `--csr` is not specified).

**COMMENTS/WORKAROUNDS**
While investigating this I also found we’re not returning an error when `--csr file:` is specified with `--key-type`, `--key-size`, and/or `--key-curve`, they’re just being silently ignored.  When we fix this bug we should add a check for that condition that return an error similar to the one we return when `--csr file:` is specified with `--cn`.

**Comment by wgoulet** [comment]
@tr1ck3r FYI on a whim I tried to reproduce this issue with a fresh build of vcert from master and when I executed these exact repro steps I did not see the enrollment occur:

`wgoulet@DESKTOP-O26JR0I:~/go/src/github.com/wgoulet/vcert$ ./bin/linux/vcert enroll -u https://example.venafi.com -t XXXXXXXXXXX -z VCert\\wgoulet --cn test.venafi.example --csr test.csr --trust-bundle venqa.pem
vCert: 2020/09/25 00:55:51 unexpected -csr option: test.csr
wgoulet@DESKTOP-O26JR0I:~/go/src/github.com/wgoulet/vcert$`

The behavior is still incorrect; as you point out we should still note that the csr argument cannot be used when cn is present, but the bigger issue you noted (silently ignoring and enrolling with local CSR generation) did not happen on my build.

**Comment by tr1ck3r** [comment]
Thank you @wgoulet.  This was an old bug from the private backlog that I just migrated here so we can retire the private backlog. 
Apparently was inadvertently (partially) fixed when the CLI framework was migrated to [urfave/cli](https://github.com/urfave/cli) earlier this year.  Thank you for the PR we'll review and get it merged soon.

**Comment by wgoulet** [comment]
@tr1ck3r Ah makes sense; in any case glad to help!
