### ISSUE TITLE
Automated downloads of vcert release artifacts

### ISSUE THREAD

**Issue by alexellis** [Venafi/vcert#145]
**BUSINESS PROBLEM**

As part of a Venafi Development Fund project, we want to download vcert in an automated fashion.

In general binary release names are predictable so that given a version number, a URL can always be constructed by convention:

For example:

https://github.com/owner/repo/releases/download/v4.11.2/tool-darwin
https://github.com/owner/repo/releases/download/v4.11.2/tool-4.11.2-darwin

Template:
https://github.com/OWNER/REPO/releases/download/vVERSION/NAME-VERSION-OS

In the case of the vcert binaries, there is something which I assume is a build number along with the version which breaks the convention and makes it impossible to generate a download URL without knowing the build number.

https://github.com/owner/repo/releases/download/v4.11.2/tool-4.11.2-BUILDNUMBER-darwin

**PROPOSED SOLUTION**

Remove the BUILDNUMBER from subsequent binary names going forward.

**CURRENT ALTERNATIVES**

Using the GitHub API to iterate files is potentially an option but not for the tool in question which must work without using a GitHub API token or the anonymous limit of 50 requests per hour.

Here is the code used in arkade to download CLIs: [tools.go](https://github.com/alexellis/arkade/blob/master/pkg/get/tools.go)

**VENAFI EXPERIENCE**

I would like to add `arkade get vcert` to the arkade tooling as an additional part of the [development fund project for arkade](https://marketplace.venafi.com/details/arkade-by-openfaas/)

**Comment by tr1ck3r** [comment]
@alexellis thank you for your feedback.  We've been thinking about removing the build number from the release artifact names since we enable automated releases earlier this year.  If we drop the build number from the naming convention and also move to distributing the VCert binary in a zip archive, will that meet your needs?  The Linux download file, for example, would be `vcert_v4.11.3_linux.zip` and would contain an executable called `vcert`.

**Comment by alexellis** [comment]
Thanks for the quick response 👋  I wouldn't necessarily recommend the zip, it just adds more work for consumers. Your binary release is already quite lean for a Go CLI.

**Comment by tr1ck3r** [comment]
@alexellis In this case the zip archive isn't as much about reducing the size of the download as it is a workaround for web browsers that are currently flagging the VCert executables as a security concern, and for the invocation command to be consistent from release to release (i.e. you always just run "vcert").  So we'd effectively be trading having to rename the executable for having to extract it from a zip file. Basically aligning with what HashiCorp is doing with their releases. Can you work with it being a zip file in your integration?

**Comment by alexellis** [comment]
Yes.

**Comment by tr1ck3r** [comment]
This request has been addressed beginning with the [v4.12.0](https://github.com/Venafi/vcert/releases/tag/v4.12.0) release 😃
