### ISSUE TITLE
vcert cli enroll/pickup pkcs12 output format fails (service generated CSR): failed to encode pkcs12: private key error

### ISSUE THREAD

**Issue by faisalrazzak** [Venafi/vcert#147]
**PROBLEM SUMMARY**
vcert cli fails to encode pkcs12 and throws error. I am trying to enroll/pickup a certificate whose CSR was service generated. The output format pem and json are working as expected, however, if the --format pkcs12 is specified following error is thrown: 

**`vCert: 2021/01/04 14:26:03 Failed to output the results: failed to encode pkcs12: private key error(3): x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)`**

**STEPS TO REPRODUCE**

**Enroll**
`.\vcert.exe enroll -u <TPP_URL> -z 'vcert-test' --cn gymservice01.burlingtonhack.ca --csr service --format pkcs12 --file serviceout.pem --key-password newPassw0rd! -t <TOKEN> --trust-bundle .\bundle.pem --verbose`

**Pickup:** 
`.\vcert.exe pickup -u <TPP_URL> --format pkcs12 --file service.pem --key-password newPassw0rd! -t <TOKEN> --trust-bundle .\bundle.pem --verbose --pickup-id "<cert-id>"`

**EXPECTED RESULTS**

A p12 file should be the output.

**ACTUAL RESULTS**

vCert: 2021/01/04 14:33:15 Failed to output the results: failed to encode pkcs12: private key error(3): x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)

**ENVIRONMENT DETAILS**

- Windows 10.
- vcert.exe version v4.11.0+1092

**COMMENTS/WORKAROUNDS**

**Comment by tr1ck3r** [comment]
@faisalrazzak I think this may be related to https://github.com/Venafi/vcert/issues/41.  Can you confirm your "Private Key PBE Algorithm" policy in TPP is set to "Low security but good system compatibility (MD5 DES)" as is required?  Go currently [lacks support](https://github.com/golang/go/issues/8860) for password encrypted PKCS#8 private keys so that's blocking us from going that route.  Ultimately we could address this by updating VCert to download the PKCS#12 keystore instead of constructing it itself from the certificate, private key, and chain certificates but that would be a fairly significant refactor.

**Comment by tr1ck3r** [comment]
Should have mentioned this as well:  https://github.com/Venafi/vcert/issues/135

**Comment by faisalrazzak** [comment]
![image](https://user-images.githubusercontent.com/6964392/103573479-4d14b700-4e9c-11eb-8b12-3ae0f72a42ea.png)

The error message is different from other open tickets. Plus configuring any value for "Private Key PBE Algorithm" throws similar error.

**Comment by tr1ck3r** [comment]
@faisalrazzak What version of TPP are you using?  Just want to make sure it is not 20.3.0 because there was a bug in that version that caused the same result you are seeing.

**Comment by faisalrazzak** [comment]
Thank you @tr1ck3r 
The issue only occurs on TPP version 20.3. I tested with TPP version 20.4 and can successfully download certificates with pkcs12 format. Both **enroll** & **pickup** sub-commands are working.

**Comment by tr1ck3r** [comment]
You're welcome @faisalrazzak.  The issue I mentioned was addressed in 20.3.1 which replaced 20.3.0 as the generally available 20.3 release for customer consumption.
