### ISSUE TITLE
Ability to check validity of OAUTH token using vcert cli

### ISSUE THREAD

**Issue by faisalrazzak** [Venafi/vcert#150]
**BUSINESS PROBLEM**

Teams managing security credentials for different vendor applications through CI/CD pipelines also need the ability to constantly check the validity of tokens. This can help in building automated workflows where if a OAUTH token has expired, a new OAUTH token is automatically requested via Refresh Tokens **(or)** stored credentials.

**PROPOSED SOLUTION**

Introduce a new sub-command **token** and a parameter **checkvalidity**. The output of this command should be **true** or **false**, something that can be easily consumed in pipelines and chained with other tasks in pipelines.

`vcert token --checkvalidity` 

**CURRENT ALTERNATIVES**

N/A

**Comment by tr1ck3r** [comment]
https://github.com/Venafi/vcert/tree/tpp-cred-mgmt
