### ISSUE TITLE
Ability to revoke OAUTH token using vcert cli

### ISSUE THREAD

**Issue by faisalrazzak** [Venafi/vcert#151]
**BUSINESS PROBLEM**

Due to different compliance or security requirements customers may need to revoke/delete OAUTH tokens once different tasks associated with TPP have completed. OAUTH tokens are generally issued for longer during and the idea is that re-authentication of credentials is minimized, however, customers may have shorter during tasks as well where revoking a token after the task is finished will make more sense.

**PROPOSED SOLUTION**

Introduce a new sub-command **token** and a parameter **revoke/delete**. This will remove the issued OAUTH token. The output of this command should be **true** or **false**, something that can be easily consumed in pipelines and chained with other tasks in pipelines.

`vcert token --delete`

**or**

`vcert token --revoke`

**CURRENT ALTERNATIVES**

N/A

**Comment by tr1ck3r** [comment]
https://github.com/Venafi/vcert/tree/tpp-cred-mgmt
