### ISSUE TITLE
Attempting to use --san-email or --san-ip results in failure

### ISSUE THREAD

**Issue by gdbarron** [Venafi/vcert#155]
**PROBLEM SUMMARY**
Attempting to use --san-email or --san-ip results in failure; --san-dns works fine

**STEPS TO REPRODUCE**
`vcert.exe enroll -k <guid> -cn three-san-types.venafi.example -z <guid> --san-email greg@jagtechnical.com`
or
`vcert.exe enroll -k <guid> -cn three-san-types.venafi.example -z <guid> --san-ip 10.20.30.40`

**EXPECTED RESULTS**
Certificate created

**ACTUAL RESULTS**
```
vcert.exe enroll -k <guid> --cn three-san-types.venafi.example -z <guid> --san-email greg@jagtechnical.com
Enter key pass phrase:****
Verifying - Enter key pass phrase:****
vCert: 2021/01/28 22:33:47 Successfully connected to Venafi Cloud
vCert: 2021/01/28 22:33:47 Successfully read zone configuration for <guid>
vCert: 2021/01/28 22:33:47 Successfully created request for three-san-types.venafi.example
vCert: 2021/01/28 22:33:47 vcert error: server error: Unexpected status code on Venafi Cloud zone read. Status: 412 Precondition Failed
Error Code: 10733 Error: SAN value of type rfc822Name must not be specified
```
```
vcert.exe enroll -k <guid> --cn three-san-types.venafi.example -z <guid> --san-ip 10.20.30.40
Enter key pass phrase:****
Verifying - Enter key pass phrase:****
vCert: 2021/01/28 22:33:59 Successfully connected to Venafi Cloud
vCert: 2021/01/28 22:33:59 Successfully read zone configuration for <guid>
vCert: 2021/01/28 22:33:59 Successfully created request for three-san-types.venafi.example
vCert: 2021/01/28 22:33:59 vcert error: server error: Unexpected status code on Venafi Cloud zone read. Status: 412 Precondition Failed
Error Code: 10733 Error: SAN value of type iPAddress must not be specified
```
**ENVIRONMENT DETAILS**
Venafi Cloud, vCert v4.12.1 on Windows

**COMMENTS/WORKAROUNDS**
hopefully not something I'm doing wrong...

**Comment by wgoulet** [comment]
Hi @gdbarron ,

Currently Venafi Cloud only supports issuing TLS server certificates which is why we returned the error code indicating those extension types are not accepted.

Thanks,
Walter

**Comment by gdbarron** [comment]
@wgoulet, glad it was something simple, apologize I didn't notice that.  Thanks for the quick response.

**Comment by wgoulet** [comment]
No problem and thanks for your contribution to our community!
