### ISSUE TITLE
Error 20216 message has application and template names swapped

### ISSUE THREAD

**Issue by gdbarron** [Venafi/vcert#157]
**PROBLEM SUMMARY**
Error 20216, when application is found, but issuing template isn't, has the names reversed

**STEPS TO REPRODUCE**
`vcert enroll -z myapp\mytemplate` where myapp exists and mytemplate does not

**EXPECTED RESULTS**
Error Code: 20216 Error: No certificate issuing template with alias **mytemplate** has been assigned to application with name **myapp**

**ACTUAL RESULTS**
Error Code: 20216 Error: No certificate issuing template with alias **myapp** has been assigned to application with name **mytemplate**

**ENVIRONMENT DETAILS**
vcert 4.13 pointing to outagepredict

**COMMENTS/WORKAROUNDS**

**Comment by tr1ck3r** [comment]
Thank you @gdbarron This is actually a :bug: on the Venafi Cloud side so I'll need to shepherd it through internally but we'll get it resolved.

**Comment by tr1ck3r** [comment]
@gdbarron the fix for this was deployed to Venafi Cloud yesterday.
