### ISSUE TITLE
vCert defaults to Server Certificate Type in TPP regardless of Certificate Template used

### ISSUE THREAD

**Issue by jmg421** [Venafi/vcert#183]
We believe vCert is somehow being hard coded to create a Server Certificate object in TPP.  The desired change would be to allow the Certificate type to be automatically detected by TPP (e.g. for Client Authentication Certificates/Templates)

**Comment by visual-est** [comment]
@tr1ck3r I have tried the change and it works. However, I have not ran the tests :) I don't have environment.
