### ISSUE TITLE
determine if cert exists using tpp

### ISSUE THREAD

**Issue by Gl4di4torRr** [Venafi/vcert#21]
I am trying to verify if a certificate already exists using the tpp client.

**Comment by Gl4di4torRr** [comment]
I can open a PR for this kind of example if it's needed.

**Comment by Gl4di4torRr** [comment]
Looks like I am looking for an example on using this method.

https://github.com/Venafi/vcert/blob/a6785701a8ca8c9bece7ca1643d287fceb047dd2/pkg/certificate/certificate.go#L249

**Comment by arykalin** [comment]
Hi, you need just to check if it exists or check that it is valid?
You can look into our tests for Vault PKI import plugin - https://github.com/Venafi/vault-pki-monitor-venafi/blob/master/plugin/pki/path_import_queue_test.go#L195-L232
But we use RetrieveCertificate so we can also check that certificate have parameters we want.

**Comment by mr-tron** [comment]
What do you know about certificate then you are going to check existing? You can search certificate by cn, pickup id or thumbprint. 
`CheckCertificate` it`s about checking that issued certificate contains same data as your request.

**Comment by Gl4di4torRr** [comment]
@arykalin @mr-tron 

Background if you want: I am working on a Kubernetes/Openshift [certificate operator](https://github.com/redhat-cop/cert-operator) that can create certificates in Venafi. Specifically, [here](https://github.com/redhat-cop/cert-operator/blob/master/pkg/certs/venafi.go) is the Venafi integration. However, if you're running Kubernetes/Openshift in a multi-cluster or multi-datacenter scenario, we have an issue where we are overriding the certificate.

For example, I create `myapp.com` certificate and store it in Venafi and attach that certificate to my route in DataCenter1. DataCenter2 then creates a certificate for `myapp.com` and the certificate is invalid in DataCenter1. 

I am looking for documentation/examples of verifying the existence and validity of a certificate in Venafi. I am also willing to help contribute more documentation/examples if their is a "gap". Thanks!

@arykalin Looked high-level at your link, that may work. I'll do some more investigating and let you know.

**Comment by arykalin** [comment]
@Gl4di4torRr did you think about requesting certificates from TPP rather then importing them? This is approach cert-manager do - https://github.com/jetstack/cert-manager/tree/master/pkg/issuer/venafi

**Comment by arykalin** [comment]
Oh, sorry, didn't check you code and thought that you creating certificate locally and then importing it into Venafi.

**Comment by Gl4di4torRr** [comment]
@arykalin yeah, i am aware of that project. We will probably integrate with them down the road. But I got pulled into another task before this one (new prioritization :) ). It will be a couple of weeks until I get back to this one. Just FYI. I will take a look at the links provided soon.

**Comment by Gl4di4torRr** [comment]
@arykalin after looking at your example, i don't have the "certText". I will basically have a hostname that is provided from the user. From that, I need to check if a cert exists and retrieve the certificate. I went down a rabbit hole through the code... But decided not to dive too far down in the implementation.

**Comment by arykalin** [comment]
@Gl4di4torRr could you clarify what information about certificate you will have? As @mr-tron said you can search certificate by cn, pickup id or thumbprint.

**Comment by Gl4di4torRr** [comment]
@arykalin @mr-tron I was able to retrieve the cert like this (like @mr-tron comment)

```
pickupId := "\\VED\\Policy\\" + os.Getenv("VENAFI_CERT_ZONE") + "\\" + host
	retrieveRequest := &certificate.Request{
		PickupID:        pickupId,
		Timeout:         180 * time.Second,
	}
```

Sorry for the confusion.
