### ISSUE TITLE
Support headless registration for Venafi as a Service

### ISSUE THREAD

**Issue by tr1ck3r** [Venafi/vcert#212]
_Venafi as a Service_ recently added a feature called "headless registration" that allows developers to  register for VaaS (and create a new company tenant if one doesn't already exist) without having to use a web browser and providing only their company email address.  VCert SDK should be updated to support this feature and VCert CLI should expose it through the existing `getcred` action.
```
vcert getcred [-u <url>] --email <email address> [--password <password>] [--format (text|json)]
```
If the CLI user specifies the new `--email` parameter then it is interpreted as a request to headlessly register for VaaS.  The output should display the inactive API key and tell the user to check their email inbox for an email with a link to activate (unless `--format json` is used in which case the output should include `apiKey` data from the API response; i.e. no messaging about the activation email).  The `--password` parameter should be optional mirroring the API call; when supplied, the specified password will allow the user to log into the VaaS web console assuming the user wasn't previously registered.  If a user has previously registered and their account has been configured to allow reset, headless registration can be used to rotate their API key (get a new one) which only becomes active if a link is clicked in an email triggered by the reset.  If the user's account does not allow reset an error is returned that should be output (true for any error).  As with other actions, the `--url` parameter overrides the https://api.venafi.cloud URL allowing for non-production testing by Venafi engineers. 
```
POST /v1/useraccounts
{
  "userAccountType": "API",
  "username": "person@company.com",
  "password": "myPassw0rd?"
}
```

Response includes unnecessary and mostly redundant data in "user" and "company" so those should simply be discarded.
```
HTTP 201 Created
{
    "user": {
        ...
    },
    "company": {
        ...
    },
    "apiKey": {
        "key": "aaaaaaaa-aaaa-aaaa-aaaaaaaaaaaaaaaaa",
        "userId": "bbbbbbbb-bbbb-bbbb-bbbbbbbbbbbbbbbbb",
        "username": "person@company.com",
        "companyId": "cccccccc-cccc-cccc-ccccccccccccccccc",
        "apiVersion": "ALL",
        "apiKeyStatus": "PENDING_ACTIVATION",
        "creationDate": "2022-03-16T15:40:38.533+00:00",
        "validityStartDate": "2022-03-16T15:40:38.533+00:00",
        "validityEndDate": "2022-09-12T15:40:38.533+00:00"
    }
}
```

**Comment by marcos-albornoz** [comment]
Implemented on [v4.20.1](https://github.com/Venafi/vcert/tree/v4.20.1)
