### ISSUE TITLE
Digitally signed vcert

### ISSUE THREAD

**Issue by amkhan1978** [Venafi/vcert#214]
**BUSINESS PROBLEM**
vcert is being used by many of our team and i have noticed that it is not digitally signed. 

**PROPOSED SOLUTION**
The current vcert is not signed. Is it possible to get vcert signed by PGP or any other publicly available method?

**CURRENT ALTERNATIVES**

**VENAFI EXPERIENCE**

**Comment by luispresuelVenafi** [comment]
This have been address in [release v4.21.0](https://github.com/Venafi/vcert/releases/tag/v4.21.0)
