### ISSUE TITLE
Renew method does not properly output a PKCS#12 file

### ISSUE THREAD

**Issue by wilddev65** [Venafi/vcert#233]
**PROBLEM SUMMARY**
The 'vcert renew' method does not output a file in pkcs#12 format

**STEPS TO REPRODUCE**
Configure vcert to request an existing certificate be renewed;
vcert.exe renew -u https://tpp.server.com -t QonTHgobfxXfOaT1LDjdSQ== --csr service --format pkcs12 --chain ignore --file test-renew2 --key-password Passcode123! --thumbprint 1EB694525083DDCC6EB9394B0F99033042B5BC4A

**EXPECTED RESULTS**
Vcert renews certificate in TPP and  successfully retrieves then outputs to pkcs#12 file in directory.

**ACTUAL RESULTS**
vCert: 2022/06/14 12:46:48 Successfully connected to Trust Protection Platform 
vCert: 2022/06/14 12:46:49 Fetched the latest certificate. Serial: 12000001c7423f0c206220154a0001000001c7, NotAfter: 2024-06-13 18:14:51 +0000 UTC 
vCert: 2022/06/14 12:46:49 Successfully created request for 1EB694525083DDCC6EB9394B0F99033042B5BC4A 
vCert: 2022/06/14 12:46:49 Successfully posted renewal request for 1EB694525083DDCC6EB9394B0F99033042B5BC4A, will pick up by \VED\Policy\Certificates\vcert-test\test-renew2 
vCert: 2022/06/14 12:46:49 Issuance of certificate is pending... 
vCert: 2022/06/14 12:46:54 Successfully retrieved request for \VED\Policy\Certificates\vcert-test\test-renew2 
vCert: 2022/06/14 12:46:54 Failed to output the results: failed to encode pkcs12: unexpected private key PEM type: ENCRYPTED PRIVATE KEY

**ENVIRONMENT DETAILS**
vcert version 4.19 for windows
TPP 21.1.0

**Comment by luispresuelVenafi** [comment]
This have been addressed in [release v4.21.0](https://github.com/Venafi/vcert/releases/tag/v4.21.0)
