### ISSUE TITLE
Error: Unexpected status code on TPP Certificate Request.  Status:  400 Bad Request,{"Error":"Need a certificate authority (CADN).\u000d\u000a"}

### ISSUE THREAD

**Issue by manju125** [Venafi/vcert#245]
Getting below issue when i tried creating the resource from terraform. 
---------------------------------------------------------------------------------------------------
venafi_certificate.cert: Creating...

Error: Unexpected status code on TPP Certificate Request.
 Status:
 400 Bad Request, check Error in response for details.. 
 Body:
 {"Error":"Need a certificate authority (CADN).\u000d\u000a"}

---------------------------------------------------------------------------------------------------

on Postman, its returning 200 OK for request. 

Here is the terraform configuration for the certificate

resource "venafi_certificate" "cert" {
  common_name       = var.common_name
  algorithm         = "RSA"
  rsa_bits          = "2048"
  san_dns           = var.san_dns
  expiration_window = 1440
  #key_password      = var.cert_password
}

**Comment by luispresuelVenafi** [comment]
Hi @manju125 thank you for reaching out.

If this an issue that is only related to our Terraform provider? Just asking to see if we migrate this issue to the Terraform provider project issue.

That error is very odd to be brought from any of our open source products. It seems to be related for the current platform you are using. Could you share which version you are using from both TPP and our Terraform provider? From my side, I recall seeing that error when the `zone` where you are trying to issue a certificate has not a template properly set (which is very odd to be properly working from postman, as you mentioned). Could you confirm with your TPP admin?
Also, could you share more information about the configuration of the policy you are using? That'd be very helpful

**Comment by tr1ck3r** [comment]
@manju125 that error is most commonly due to not having a CA template assigned by policy to your Trust Protection Platform zone (policy folder).  It can also be due to insufficient permissions for the TPP user.  Can you please confirm you have a CA template assigned to the policy folder and, if so, what permissions the user has to the policy folder in TPP?

**Comment by manju125** [comment]
@tr1ck3r : You were right, i was passing the wrong path where i missed a folder.

Thanks @tr1ck3r and @luispresuelVenafi for your time to look into it.

**Comment by manju125** [comment]
@tr1ck3r : You were right, i was passing the wrong path where i missed a folder.

Thanks @tr1ck3r and @luispresuelVenafi for your time to look into it.
