### ISSUE TITLE
Add new methods for tpp connector

### ISSUE THREAD

**Issue by Geovanni89** [Venafi/vcert#248]
**BUSINESS PROBLEM**
vSSH command line utility is using now some logic to get the system version and user’s identity which belongs to vCert. Those methods should be consumed directly from vCert packages.

**PROPOSED SOLUTION**
We are planning to expose an existing endpoint on vCert to get the system version and create an internal method to get user’s identity and add the returned data on the tpp connector 

**CURRENT ALTERNATIVES**
Currently vSSH has a file with the necessary methods and vcert logic to work properly.

**Comment by luispresuelVenafi** [comment]
This was addressed in VCert version [v4.22.1](https://github.com/Venafi/vcert/releases/tag/v4.22.1)
