### ISSUE TITLE
Venafi Curl Document 

### ISSUE THREAD

**Issue by rahul6941** [Venafi/vcert#282]
looking for any curl documentation to interact with  Venafi API . Please send me url for this . Thanks!

**Comment by KBo0o** [comment]
Check out https://developer.venafi.com/tlsprotectcloud/reference/tls-protect-overview

You can select for examples using cURL

**Comment by rahul6941** [comment]
Thanks for help!

**Comment by rahul6941** [comment]
Sorry . this is like Venafi Saas documnetattion but we installed Venafi on prem and I am looking to use Venafi API
