### ISSUE TITLE
Add support for Win11 ARM

### ISSUE THREAD

**Issue by Pmaraveyias** [Venafi/vcert#296]
**BUSINESS PROBLEM**
Some users are beginning to use Win11 ARM machines and may need to use vcert on the servers. While emulation may allow running the x86 or x64 versions an arm specific version would be better

**PROPOSED SOLUTION**
Add native Windows arm64 to the build versions

**CURRENT ALTERNATIVES**
Use native emulation to run the existing Windows binaries

**Comment by BeardedPrincess** [comment]
This is being investigated now.
