### ISSUE TITLE
vCert CLI playbook preview PEM files not encrypted even when keyPassword provided

### ISSUE THREAD

**Issue by BeardedPrincess** [Venafi/vcert#309]
**PROBLEM SUMMARY**
In the vCert 5.0 playbook (preview) functionality, when specifying an installation of type PEM, the resulting key file is stored in unencrypted format, even if `keyPassword` is specified in the request.

**STEPS TO REPRODUCE**
Run a playbook that specifies a PEM installation, make sure keyPassword is set in the request. Examine the resulting key file - it's unencrypted. Confirmed behavior in code within the PEM installation.

**EXPECTED RESULTS**
Key file should be encrypted using the specified `keyPassword`

**ACTUAL RESULTS**
Key file is not encrypted

**ENVIRONMENT DETAILS**
vCert 5.0 preview build (vcp) 

**COMMENTS**
Related to another issue #310 as well as proposed enhancement (will link here too). Essentially, the keyPassword should be removed from the certificate request struct, and moved into the PEM installation directly. Not all installations can take a password, and some require it. Moving it to the installation section provides much needed clarity in the config file.

**Comment by luispresuelVenafi** [comment]
@BeardedPrincess does this appliy for both TPP and VaaS?

**Comment by BeardedPrincess** [comment]
Yes. This issue is unrelated to the source of the private key: Generated locally, generated by TPP, or generated by VaaS. It is related to how the files are being written to disk in the PEM driver (app/installer/PEM.go). There is no check to whether the resulting PEM should be encrypted or not, and always writes the unencrypted version.
