### ISSUE TITLE
CSR recognition problems

### ISSUE THREAD

**Issue by MrCoedzAlittle** [Venafi/vcert#36]
If the CSR header is either missing, or contains "NEW" in the header, vcert can't identify that the file is a csr.   

Sample CSR generated by a tool:

-----BEGIN NEW CERTIFICATE REQUEST-----
MIICvDCCAaQCAQAwdzELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFV0YWgxDzANBgNV
BAcMBkxpbmRvbjEWMBQGA1UECgwNRGlnaUNlcnQgSW5jLjERMA8GA1UECwwIRGln
aUNlcnQxHTAbBgNVBAMMFGV4YW1wbGUuZGlnaWNlcnQuY29tMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8+To7d+2kPWeBv/orU3LVbJwDrSQbeKamCmo
wp5bqDxIwV20zqRb7APUOKYoVEFFOEQs6T6gImnIolhbiH6m4zgZ/CPvWBOkZc+c
1Po2EmvBz+AD5sBdT5kzGQA6NbWyZGldxRthNLOs1efOhdnWFuhI162qmcflgpiI
WDuwq4C9f+YkeJhNn9dF5+owm8cOQmDrV8NNdiTqin8q3qYAHHJRW28glJUCZkTZ
wIaSR6crBQ8TbYNE0dc+Caa3DOIkz1EOsHWzTx+n0zKfqcbgXi4DJx+C1bjptYPR
BPZL8DAeWuA8ebudVT44yEp82G96/Ggcf7F33xMxe0yc+Xa6owIDAQABoAAwDQYJ
KoZIhvcNAQEFBQADggEBAB0kcrFccSmFDmxox0Ne01UIqSsDqHgL+XmHTXJwre6D
hJSZwbvEtOK0G3+dr4Fs11WuUNt5qcLsx5a8uk4G6AKHMzuhLsJ7XZjgmQXGECpY
Q4mC3yT3ZoCGpIXbw+iP3lmEEXgaQL0Tx5LFl/okKbKYwIqNiyKWOMj7ZR/wxWg/
ZDGRs55xuoeLDJ/ZRFf9bI+IaCUd1YrfYcHIl3G87Av+r49YVwqRDT0VDV7uLgqn
29XI1PpVUNCPQGn9p/eX6Qo7vpDaPybRtA2R7XLKjQaF9oXWeCUqy1hvJac9QFO2
97Ob1alpHPoZ7mWiEuJwjBPii6a9M9G30nUo39lBi1w=
-----END NEW CERTIFICATE REQUEST-----

vcert cannot identify that this is a CSR.

In order to get vcert to process, i have to use a workaround using openSSL to pre-process the CSR and output it in a way VCERT understands.  

Example Pre-Process line:
cat CSRTOPROCESS.csr |openssl req -out OUT.CSR -outform PEM

This fixes the header in the OUT.CSR.

ideally, since Venafi will accept input with no header, and with the original header stated above, vcert should also be able to validate the CSR is legit.

Related support ticket:
https://support.venafi.com/hc/requests/48743

**Comment by tr1ck3r** [comment]
Thank you @MrCoedzAlittle, I've added this issue to the work we have targeted for our next development sprint.  We're planning to release a new version of the VCert CLI soon and we'll do our best to get this in.
