### ISSUE TITLE
vCert 5.0.1 reports  Version: Unknown and Build Timestamp: Unknown

### ISSUE THREAD

**Issue by Ben-FB** [Venafi/vcert#365]
**PROBLEM SUMMARY**

vCert 5.0.1 reports  Version: Unknown and Build Timestamp: Unknown.

**STEPS TO REPRODUCE**

Run vcert.exe --help.

**EXPECTED RESULTS**

The Version and Build Timestamp will report a correct version and timestamp as seen in prior versions.

```
.\vcert_v5.0.0_windows\vcert.exe --help
Venafi Certificate Utility
   Version: v5.0.0
   Build Timestamp: 20230731.235435

USAGE:
   vcert.exe [global options] command [command options] [arguments...]
```

**ACTUAL RESULTS**

We've verified that the SHA1 hash are correct.
```
Get-FileHash -Algorithm SHA1 * | Select-Object Hash,Path

Hash                                     Path
----                                     ----
F0632A9C701B4D4A7E75F691AE62270B3A7D6408 vcert_v5.0.1_windows.zip
1A6E0F79C3E8D2649734E77E272F851B14C0A3F3 vcert_v5.0.1_windows86.zip
```

Testing with 5.0.1 for Windows.
```
.\vcert_v5.0.1_windows\vcert.exe --help
Venafi Certificate Utility
   Version: Unknown
   Build Timestamp: Unknown

USAGE:
   vcert.exe [global options] command [command options] [arguments...]
```

Testing with 5.0.1 for Windows x86.
```
.\vcert_v5.0.1_windows86\vcert86.exe --help
Venafi Certificate Utility
   Version: Unknown
   Build Timestamp: Unknown

USAGE:
   vcert86.exe [global options] command [command options] [arguments...]
```

**ENVIRONMENT DETAILS**

vcert 5.0.1

**COMMENTS/WORKAROUNDS**

This is a low priority visual issue.

**Comment by BeardedPrincess** [comment]
The issue in the build pipeline causing this has been fixed. The latest RC release for 5.1 should have this fix in it already, and subsequent release builds will now too. Test out https://github.com/Venafi/vcert/releases/tag/v5.1.0-rc1

**Comment by rvelaVenafi** [comment]
As @BeardedPrincess confirmed, this issue is fixed and will be closed.
