### ISSUE TITLE
keyType of ec or ecc results in unknown key type error

### ISSUE THREAD

**Issue by yavin06** [Venafi/vcert#407]
**PROBLEM SUMMARY**
vcert playbook claims unknown key type when  specifying ecc.

We have specified keyType: ecc   (also tried with just ec) and different keyCurves as documented on the readme (https://github.com/Venafi/vcert/blob/master/README-PLAYBOOK.md)

Here is a snippet from the playbook:
certificateTasks:
  - name: renew_cert # Task Identifier
    renewBefore: 31d
    setEnvVars: ["thumbprint", "serial"] #will set environment variables VCERT_TASKNAME_THUMBPRINT and VCERT_TASKNAME_SERIAL
    request:
      chain: root-last
      csr: service
      keyType: ecc
      keyCurve: p384
      sanDNS:
        -
      subject:
        commonName: cn-redacted.company.com
        country:
        locality:
        state:
        organization:
        orgUnits:
          -
      zone: Certificates\\Test_policy\\

When we run the playbook, we get the following error:

/usr/local/bin/vcert run --file /opt/vcert_playbooks/vcert_playbook.yaml --debug
2023-10-30T12:01:22.715-0400    INFO    vcert/playbook.go:103   running playbook file   {"file": "/opt/vcert_playbooks/vcert_playbook.yaml"}
2023-10-30T12:01:22.715-0400    DEBUG   vcert/playbook.go:104   debug is enabled
2023-10-30T12:01:22.715-0400    DEBUG   parser/reader.go:90     reading from local file system
2023-10-30T12:01:22.716-0400    ERROR   vcert/playbook.go:108   failed to unmarshal the playbook file: vcert error: unknown key type: ECC
main.doRunPlaybook
        /vcert/cmd/vcert/playbook.go:108
github.com/urfave/cli/v2.(*Command).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274
github.com/urfave/cli/v2.(*Command).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267
github.com/urfave/cli/v2.(*App).RunContext
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332
github.com/urfave/cli/v2.(*App).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main
        /vcert/cmd/vcert/main.go:155
runtime.main
        /usr/local/go/src/runtime/proc.go:250

**STEPS TO REPRODUCE**
Specify ec or ecc as a keyType for a playbook

**EXPECTED RESULTS**
The key should be created as ecc.

**ACTUAL RESULTS**
We get the error above.

**ENVIRONMENT DETAILS**
running TPP version 23.1.3 and vcert version 5.1.1 on linux

**COMMENTS/WORKAROUNDS**
ecdsa seems to work, but it's not ecc

**Comment by rvelaVenafi** [comment]
Yes, looks like our documentation is misleading. Only supported values by the code are:
`RSA`, `ECDSA` and `ED25519`

**Comment by yavin06** [comment]
Are there plans to enable support for ecc?

**Comment by luispresuelVenafi** [comment]
@yavin06 don't understand what you mean, if you are meaning to create keys using Elliptic Curve Cryptography, `ECDSA` or `ED25519` are your way to go

**Comment by yavin06** [comment]
sorry.. @luispresuelVenafi, got twisted with too many things on my side.. 

I was thinking about aligning the terminology between TPP and vcert.. in the TPP policy, the key algorithm options are either RSA or ECC.

**Comment by luispresuelVenafi** [comment]
No worries @yavin06, did if work for you after doing the change?

**Comment by yavin06** [comment]
I'm getting this error now:

2023-10-31T07:50:40.842-0400    ERROR   service/service.go:88   error preparing certificate for installation    {"error": "could not prepare certificate and key: pkcs8: only PKCS #5 v2.0 supported"}
github.com/Venafi/vcert/v5/pkg/playbook/app/service.Execute
        /vcert/pkg/playbook/app/service/service.go:88
main.doRunPlaybook
        /vcert/cmd/vcert/playbook.go:145
github.com/urfave/cli/v2.(*Command).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274
github.com/urfave/cli/v2.(*Command).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267
github.com/urfave/cli/v2.(*App).RunContext
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332
github.com/urfave/cli/v2.(*App).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main
        /vcert/cmd/vcert/main.go:155
runtime.main
        /usr/local/go/src/runtime/proc.go:250
2023-10-31T07:50:40.842-0400    ERROR   vcert/playbook.go:148   error running task      {"task": "renew_cert", "error": "error preparing certificate for installation: could not prepare certificate and key: pkcs8: only PKCS #5 v2.0 supported"}
main.doRunPlaybook
        /vcert/cmd/vcert/playbook.go:148
github.com/urfave/cli/v2.(*Command).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274
github.com/urfave/cli/v2.(*Command).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267
github.com/urfave/cli/v2.(*App).RunContext
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332
github.com/urfave/cli/v2.(*App).Run
        /go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main
        /vcert/cmd/vcert/main.go:155
runtime.main
        /usr/local/go/src/runtime/proc.go:250

**Comment by luispresuelVenafi** [comment]
@yavin06 by any chance, in your TPP policy folder, in PBE Key Algorithm, do you have set:
`Insecure but good system compatibility (MD5 DES)`

if so, could you change to any of the other options? We have dropped support since VCert 4.17.0
https://github.com/Venafi/vcert/releases/tag/v4.17.0

Cloud, you let us know if this doesn't work you?

**Comment by yavin06** [comment]
@luispresuelVenafi , it's set to "high security, but low system compatibility"
![image](https://github.com/Venafi/vcert/assets/15681432/0592f8a6-4956-4856-8bfe-0f9eccad3041)


should I change it to something else?

**Comment by yavin06** [comment]
Hello.. we managed to get the vcert enroll command to work with no issues.  Here is the command with info redated:
/usr/local/bin/vcert enroll -u https://venftppserver.company.com -z Certificates\\Test_policy -cn=cn-redacted.company.com -t REDACTED --key-type ecdsa --key-curve p384 --csr service --key-file /opt/keys/server.key --cert-file /opt/certs/server.pem --format pem --key-password file:./keypassphrase

we did not change anything in the policy.  the playbook still throws the error.  I'm not sure what the difference is between running the playbook and the enroll.

Thanks!

**Comment by luispresuelVenafi** [comment]
> @luispresuelVenafi , it's set to "high security, but low system compatibility"
No, that's a good setting. You should be good with your PBE then.

This is most likely something else. I'll bring this up with my team

**Comment by luispresuelVenafi** [comment]
Hi @yavin06 

I reproduced this issue successfully, this only happens on `service` generated certificates, we have a bug. Not sure if a valid workaround for you would be using `local` generated certificates, while I work on the fix.

**Comment by yavin06** [comment]
@luispresuelVenafi , we'll give local a try and see how that works out.

**Comment by luispresuelVenafi** [comment]
Hi there @yavin06 

Were you able to test in "local" mode?

**Comment by yavin06** [comment]
Hi @luispresuelVenafi,
 Thanks for your help. We were able to test and validate the latest version fixed the issue.

Thanks again!

**Comment by luispresuelVenafi** [comment]
Solved by release VCert [v5.2.1](https://github.com/Venafi/vcert/releases/tag/v5.2.1)
