### ISSUE TITLE
Cert Binding automation

### ISSUE THREAD

**Issue by Suba91** [Venafi/vcert#417]
Hi Team,

We are testing with Vcert Automation with Venafi, and we have able to successfully test the Cert request (CAPI) with help of example yaml file to request new cert.

But we would like to check the feasibility to automate‘ Cert binding’ for the same in IIS using same Yaml file.

Also, kindly share us the options with Oauth token Authorization that we can test / any other authorization method like gMSA (group managed service account).

**Comment by BeardedPrincess** [comment]
Hi @Suba91 ,

These are great questions. I am focused on creating some additional documentation and helps for using the vCert playbook to help answer these kinds of "How do I" questions better in the future.

In the meantime, I've asked your Customer Success Manager to reach out to you to answer these questions and provide the help you need on this.  You should expect to hear from them via email soon.

**Comment by Suba91** [comment]
Hi Team,

Can we have any further updates on the below please, Thanks.

Regards,

Subashree Ethirajulu
IAM Certificate Engineering (LOCK) Team
Email: ***@***.******@***.***>

**Comment by rvelaVenafi** [comment]
@BeardedPrincess Has this issue been resolved? Can we close it?

**Comment by Suba91** [comment]
Hi,

Yes please.

Regards,

Subashree Ethirajulu
IAM Certificate Engineering (LOCK) Team
Email: ***@***.******@***.***>
