### ISSUE TITLE
Legacy PKCS12 no longer supported for playbooks

### ISSUE THREAD

**Issue by Pmaraveyias** [Venafi/vcert#431]
**PROBLEM SUMMARY**
After adding the feature to modernize the PKCS12 algorithm, use cases which require legacy p12 are no longer working with playbooks. There is currently no option to use legacy p12 in a playbook.

**STEPS TO REPRODUCE**
Request a certificate in a vcert playbook using p12 which requires legacy encryption

**COMMENTS/WORKAROUNDS**
Currently the only workarounds are downgrading to 5.2 or not using the playbook functionality

**Comment by BeardedPrincess** [comment]
This is also affecting CAPI playbook installations on windows 2016 and earlier with a red-herring error message of "invalid password" blowing up the installer powershell script execution.

**Comment by Pmaraveyias** [comment]
Addressed by #464
