### ISSUE TITLE
Feed API/Oauth token to vcert run command

### ISSUE THREAD

**Issue by kjacque95** [Venafi/vcert#434]
**BUSINESS PROBLEM**
Currently the token has to persist in the playbook or be passed as an environment variable

**PROPOSED SOLUTION**
 Have the ability to feed the oauth token to vcert at run time.  

**CURRENT ALTERNATIVES**
 none 

**VENAFI EXPERIENCE**

**Comment by BeardedPrincess** [comment]
@kjacque95 using the environment variable is the approach for passing an access / refresh token at runtime. 

```shell
export TPP_TOKEN=4321-4321-bcda-bcda-12341234
vcert run -f myPlaybook.yaml
``` 

inside the playbook refer to the variable as:

```yaml
accessToken: '{{ Env "TPP_TOKEN" }}'
```
