### ISSUE TITLE
Set the User-Agent HTTP header in requests to Venafi API server

### ISSUE THREAD

**Issue by wallrj** [Venafi/vcert#437]
**BUSINESS PROBLEM**

As an administrator of a Venafi TPP server or of a Venafi Cloud tenant, I want to know which software is being used to connect to the REST API.

Right now the `vcert` CLI and any software that uses the vcert SDK will use the [default Go HTTP client User-Agent header](https://github.com/golang/go/blob/db423dde85ad4923c2c4addb1cd96f119c7b6dc6/src/net/http/request.go#L534-L538): `Go-http-client/1.1` and the requests will be indistinguishable.

For example, if the TPP API server is being overwhelmed by a rapid repeated requests, I would like to be able to look at the IIS server logs and see from the User-Agent of the offending requests and that the requests *may* be being generated by a `vcert` command because I see `User-Agent: vcert/vX.Y.Z`.

As a maintainer of the cert-manager Venafi Issuer, I want to be able to use the vcert SDK and configure it to send `User-Agent: cert-manager/vX.Y.Z` so that the administrator of a Venafi TPP server or Venafi Cloud service, can know which software is being used to connect to the REST API. Why? Because if there is a bug in the cert-manager Venafi issuer, which causes it to not back off in the event of a failed API request, the Venafi server administrator can quickly know that cert-manager is the culprit and quickly report the bug so that it be quickly fixed.

**PROPOSED SOLUTION**

Add a default User-Agent HTTP header to the Vcert client.
Allow the User-Agent to be **easily** overridden by software that imports the Vcert SDK.

**CURRENT ALTERNATIVES**

To change the User-Agent of `vcert` CLI requires modification of the source code and recompilation.

To change the User-Agent when importing the vcert SDK requires supplying a custom `http.Client` with a [RoundTripper wrapped transport](https://github.com/cert-manager/cert-manager/pull/6865):
* https://github.com/Venafi/vcert/blob/a30535acfbeac7a1d5d1c8fe450a772d6c6faa68/config.go#L64-L65
* https://github.com/cert-manager/cert-manager/pull/6865

<img width="960" alt="image" src="https://github.com/Venafi/vcert/assets/978965/73cc91c8-afd2-4885-91cd-895c19f908f0">

**Comment by BeardedPrincess** [comment]
@wallrj I think this a valuable change for the reasons you have listed. It would also be useful to be able to identify clients and applications that are using a potentially old version of the SDK.

Do you anticipate that you will be able to submit a PR for these?
