### ISSUE TITLE
Enable configuring a default/fallback when an environment variable does not exist.

### ISSUE THREAD

**Issue by sabixx** [Venafi/vcert#471]
**BUSINESS PROBLEM**
There are cases where specific environment variables are not predefined on all systems, which could lead to potential issues as vcert expects these variables to be present. We also encounter inefficiencies by applying certain settings to all machines, even when only a few need them. This can cause unnecessary work and confusion about system setups.

**PROPOSED SOLUTION**
Allow defining a default when an environment variable is missing. 

**CURRENT ALTERNATIVES**
Need to set all environment variables on all systems.

**Comment by BeardedPrincess** [comment]
Closed by #472
