### ISSUE TITLE
Custom `http.Client`

### ISSUE THREAD

**Issue by BrandonRoehl** [Venafi/vcert#49]
**BUSINESS PROBLEM**

The Vcert SDK uses the `http.DefaultTransport` so there is no way to make two clients use separate transport layers. With the default client being used everything is in the global scope.

**PROPOSED SOLUTION**

Add a sub field to `vcert.Config` such as `Client http.Client`. Then all things that make post commands and get should do it off the internal client. Any modifications made to the client or the transport layer would be isolated then.[`http.Client`](https://golang.org/pkg/net/http/#Client) gives all the same functionality but remains isolated.

Comparing types vs pointers in this case

```go
Client http.Client // Struct
Client *http.Client // Pointer
```

Struct gains us a couple benefits over pointers such as that it come default initialized. And requires no code to use the default and no code in client to initialize it cause it can never be `nil`.

This approach gives full backwards compatibility for anyone using `DefaultTransport` as well as giving the ability to customize the client how ever someone needs, without modifying the global space.

**CURRENT ALTERNATIVES**

Example even in this repo [main_test.go line 35](https://github.com/Venafi/vcert/blob/master/example/main_test.go#L35)

```go
http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
```

This is in general poor practice cause if you have to skip verify or present custom certs or anything else there is no way to do so besides trying to cast internal data structure to a raw type then modify the global space everything needs, thus changing "defaults". This may be necessary where TPP is using a certificate that isn't validated against the root pool and acceptable but not to skip every connection your.

**VENAFI EXPERIENCE**

Will end up blocking integration work if we use this SDK.

**Comment by tr1ck3r** [comment]
@BrandonRoehl thank you for bringing this shortcoming to our attention.  I've discussed with my team and we have an alternative idea for addressing the problem that we're currently planning to implement this month.  The end goal being the same, to isolate the configuration for the HTTP client used by our package.

**Comment by BrandonRoehl** [comment]
Will we still be allowed to replace the `http.Client` at will? Thinking from a testing perspective of end to end testing calls with a client interface? As well as all the other config options we get

**Comment by mr-tron** [comment]
I have suggestion. 
1. We can stop touch `http.DefaultTransport` at all and begin to make new independent http.Transport for our requests. 
2. We don't want to add new field to vcert.Config, but we can 
2.1 add global variable inside vcert package available for monkey-patching  (something like `vcert.DefaultClient = &http.Client{blah-blah}`)
2.2 or add method `SetHTTPClient(c *http.Client)` to connector if 2.1 is not enough

**Comment by BrandonRoehl** [comment]
I'd still suggest on `vcert.Client` cause with a global there is no way to connect to two TPP instances using different clients still.

Sorry if I'm bad at explaining. Would you guys be opposed to me opening a PR maybe explain what I am thinking?

**Comment by mr-tron** [comment]
Or. I understood. 2.2 will be enough for. 
```
	c, err := vcert.NewClient(config)
	if err != nil {
		t.Fatalf("could not connect to endpoint: %s", err)
	}
	customClient := http.Client{blah-blah}
	c.SetHTTPClient(&customClient)
```
something like this.

**Comment by BrandonRoehl** [comment]
That can work! Can I inquire into the reasoning behind having this as an unexpected field on client with a setter vs an exposed field that can be mutated?

**Comment by mr-tron** [comment]
Can you try branch `http-custom-client`? It is still on our internal code review, but all automatic tests are passed. If your experience will be positive, I hope we will merge it to master.

**Comment by BrandonRoehl** [comment]
Going to pull it and take a look now

**Comment by BrandonRoehl** [comment]
This works for us! Huge thanks to @mr-tron for such a rapid turn around! This is great!
