### ISSUE TITLE
No option to add policyDn or CADN from command line

### ISSUE THREAD

**Issue by raymondhardynike** [Venafi/vcert#6]
When i try to make a request for a certificate i am greeted with this error

```
2019/02/11 15:00:30 Loading configuration from config.ini section DEFAULT
2019/02/11 15:00:30 Validating configuration section DEFAULT
vCert: 2019/02/11 15:00:30 overriding Zone value based on commandline flag
vCert: 2019/02/11 15:00:31 Successfully connected to TPP
vCert: 2019/02/11 15:00:31 Successfully read zone configuration for \myzone\Internal\
vCert: 2019/02/11 15:00:32 Successfully created request for is-venafi-working.example.com
vCert: 2019/02/11 15:00:32 Unexpected status code on TPP Certificate Request. Status: 400 Bad Request, check Error in response for details.. Body: {"Error":"Need a certificate authority (CADN).\u000d\u000a"}: {"Error":"Need a certificate authority (CADN).\u000d\u000a"}
```
I use the api in other places and find that i have to include my PolicyDN i understand from reading the code this is pulled from the zone however i do not think that is configured in our zone. I do not however use a CADN in my config for the other api calls.

**Comment by tr1ck3r** [comment]
Hi @raymondhardynike the VCert requirement for the CA template to be assigned by policy follows a long standing Venafi best practice and a design objective to keep the certificate request process simple for VCert users.  You're correct that the TPP REST APIs allow you to optionally specify the CA template (CADN) but we have no plans for the VCert CLI to support it for the aforementioned reasons.

**Comment by raymondhardynike** [comment]
okay closing

**Comment by mkorejo** [comment]
Hi @tr1ck3r,

Given this is supported via the TPP REST API, I would think it is technically feasible to update the VCert CLI such that it accepts CA template as an input param, correct? Understanding this is a deviation from Venafi best practices, my organization wants to use multiple CA templates per TPP policy and so I'm looking to update Vcert to support this.

I exposed a command-line flag `cf.caDN` and added `CADN` as a string to the `Request` struct [here](https://github.com/Venafi/vcert/blob/master/pkg/certificate/certificate.go#L133). I see `CADN` already exists in the `certificateRequest` struct [here](https://github.com/Venafi/vcert/blob/master/pkg/venafi/tpp/tpp.go#L42). I also try to populate `req *certificate.Request` with `CADN` using the following code [here](https://github.com/Venafi/vcert/blob/master/cmd/vcert/utils.go#L36):
```
	if cf.caDN != "" {
		req.CADN = cf.caDN
	}
```

Lastly, I updated the switch in `prepareRequest(req *certificate.Request, zone string)` [here](https://github.com/Venafi/vcert/blob/master/pkg/venafi/tpp/connector.go#L113) to include `CADN` like so:
```
	case certificate.LocalGeneratedCSR, certificate.UserProvidedCSR:
		tppReq = certificateRequest{
			PolicyDN:                getPolicyDN(zone),
			CADN:                    req.CADN,
			PKCS10:                  string(req.CSR),
			ObjectName:              req.FriendlyName,
			DisableAutomaticRenewal: true}

	case certificate.ServiceGeneratedCSR:
		tppReq = certificateRequest{
			PolicyDN:                getPolicyDN(zone),
			CADN:                    req.CADN,
			ObjectName:              req.FriendlyName,
			Subject:                 req.Subject.CommonName, // TODO: there is some problem because Subject is not only CN
			SubjectAltNames:         wrapAltNames(req),
			DisableAutomaticRenewal: true}
```

Not sure what else I am missing. When I invoke the VCert CLI now against a policy that does not have a CA template assigned, I experience the following:
```
./vcert enroll -tpp-url https://ven.api.myorg.com/ -tpp-user my_user -tpp-password $VENAFI_TPP_PASSWD -z 'Certificates\My Policy Subfolder\Another Subfolder' -ca-dn 'CA name' $VENAFI_CLIENT_TLS -insecure -no-prompt -csr file:openssl-csr.csr -cert-file returned_cert.pem
vCert: 2019/03/08 10:40:10 Successfully connected to TPP
vCert: 2019/03/08 10:40:10 Successfully read zone configuration for Certificates\Mastercard Cardless ATM\Pre Approved
vCert: 2019/03/08 10:40:10 Successfully created request for file:openssl-csr.csr
vCert: 2019/03/08 10:40:10 Unexpected status code on TPP Certificate Request. Status: 400 Failed to write ca dn; Error: InvalidAttributeDN. Body: {"Error":"Failed to write ca dn; Error: InvalidAttributeDN"}: {"Error":"Failed to write ca dn; Error: InvalidAttributeDN"}
```

I tried specifying `-ca-dn 'CA name'` and also `-ca-dn 'Administration\CAs\Internal\CA name'` but get the same result. If I omit `-ca-dn` against the same policy, Vcert returns a failure as expected: `{"Error":"Need a certificate authority (CADN).\u000d\u000a"}`.

Thoughts about what might be happening here? You're such a great help. Keep it up, please. :-)

**Comment by arykalin** [comment]
Hi @mkorejo could you please open new issue and add a link to this one?
