### ISSUE TITLE
Can't import vcert v4.6.0 with go 1.13 and modules enabled

### ISSUE THREAD

**Issue by bignastybryce** [Venafi/vcert#67]
**PROBLEM SUMMARY**

I am unable to import vcert into another module using golang 1.13.

**STEPS TO REPRODUCE**

From a go module repo, using go 1.13, `go get github.com/Venafi/vcert@v4.6.0`

**EXPECTED RESULTS**

The go.mod and go.sum files should be updated with the vcert version, and the module should be available to import.

**ACTUAL RESULTS**

```
go get github.com/Venafi/vcert@v4.6.0: github.com/Venafi/vcert@v4.6.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4
```

**ENVIRONMENT DETAILS**

Golang 1.13.5 on MacOS Catalina
 
**COMMENTS/WORKAROUNDS**

Using golang 1.12 allows you to `go get` the module in spite of the lack of a /v4 path, but uses a generated version in go.mod.
Here is a relevant article: https://blog.golang.org/v2-go-modules

**Comment by arykalin** [comment]
Hi @bignastybryce 
Yes, unfortunately we have this problem because we switched to go mod we didn't realize that we need different branches for version bigger than 1 (see https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning). 
We will fix it in future, for now, as workaround you can use commit number to get specific tag:
for example for 4.6.0 it will be:
```
go mod edit --require github.com/Venafi/vcert@46ed6e7
go mod tidy
go mod verify
```
or
```
go get github.com/Venafi/vcert@46ed6e7
```

**Comment by mr-tron** [comment]
We know about the problem and we are going to fix it, but it's not the most priority problem now.

As workaround you can use commit id instead tag name. For example for `v4.6.0` it is `go mod download github.com/Venafi/vcert@46ed6e7db59c8b79d9c57a27e3075548b5691760`

**Comment by bignastybryce** [comment]
Hi @arykalin,
Thanks for the response.  I went back and re-tested with go 1.13 using the commit hash, as in your post above.  That works.  I had used "@v4.6.0", which works with 1.12, but fails with the error I posted above in 1.13.
I'm mostly posting this in case someone is having a similar problem.  Don't use the semver tag to get a module that doesn't support >1 version paths with go 1.13.  Use the commit hash.
```
<prompt> credhub-venafi % go get github.com/Venafi/vcert@v4.6.0
go: finding github.com/Venafi/vcert v4.6.0
go: finding github.com/Venafi/vcert v4.6.0
go get github.com/Venafi/vcert@v4.6.0: github.com/Venafi/vcert@v4.6.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4
<prompt> credhub-venafi % go get github.com/Venafi/vcert@46ed6e7
go: finding github.com/Venafi/vcert 46ed6e7
<prompt> credhub-venafi % 
```

**Comment by wallrj** [comment]
This seems to be fixed now. I was able to [update to vcert 4.11 in cert-manager](https://github.com/jetstack/cert-manager/pull/3358)
