### ISSUE TITLE
vcert enroll returns x509: RSA key missing NULL parameters

### ISSUE THREAD

**Issue by mkorejo** [Venafi/vcert#7]
I am trying to use vcert to request/generate signed certificates and return them back to me. Here's my command invocation. FYI I have also made changes to add mTLS:

```
./vcert enroll -tpp-url https://stage.ven.api.myorg.int -tpp-user my-venafi-user -tpp-password $VENAFI_TPP_PASSWD -z 'Certificates\Pre Approved\TLS Client' $VENAFI_CLIENT_TLS -insecure -no-prompt -csr file:openssl-csr.csr -cert-file returned_cert.pem -key-file returned_key.pem
```

Here's the response:
```
vCert: 2019/02/14 12:02:13 Successfully connected to TPP
vCert: 2019/02/14 12:02:14 Successfully read zone configuration for Certificates\Pre Approved\TLS Client
vCert: 2019/02/14 12:02:14 Successfully created request for file:openssl-csr.csr
vCert: 2019/02/14 12:02:14 Successfully posted request for file:openssl-csr.csr, will pick up by \VED\Policy\Certificates\Pre Approved\TLS Client\my-openssl-csr
vCert: 2019/02/14 12:02:14 Issuance of certificate is pending...
vCert: 2019/02/14 12:02:19 Issuance of certificate is pending...
vCert: 2019/02/14 12:02:24 Issuance of certificate is pending...
vCert: 2019/02/14 12:02:29 Issuance of certificate is pending...
vCert: 2019/02/14 12:02:35 x509: RSA key missing NULL parameters
```

No certificate file or private key is returned. Any idea what this message means and how to resolve this?

**Comment by tr1ck3r** [comment]
Hi @mkorejo, that error is actually being returned by the Go language x509 public key parser when it determines the certificate is not compliant with RFC 3279 (https://tools.ietf.org/html/rfc3279#section-2.3.1).  What CA are you using to issue your certificates?  Can you share the test certificate that was enrolled when you received that error?  If you'd prefer you can email it to opensource@venafi.com.

One other thing I noticed in your command line syntax that does not cause an error but is invalid, when you generate a CSR yourself and provide it using the `-csr file:` parameter, there is no need to specify the `-key-file` parameter because VCert won't have access to the private key.

**Comment by mkorejo** [comment]
@tr1ck3r, thanks so much for the reply. I sent the test certificate to opensource@venafi.com. I forgot to note that in VEDAdmin in the policy folder, I can see the certificate object and it is in the `OK` status. Perhaps you already knew that. :-)

I think the CA behind the scenes here is custom. You can see this in the certificate I shared. I am trying to confirm whether this custom CA is based on something else though, like Microsoft AD CS.

Thanks also for the hint about the `-key-file` option. Looking forward to getting this resolved and being able to request and retrieve a certificate via vcert!

**Comment by tr1ck3r** [comment]
This is the origin of the error:  https://github.com/golang/go/blob/master/src/crypto/x509/x509.go#L990

I noticed for the sample certificate you provided that the ASN.1 sequence for the signature algorithm, sha256RSA (1.2.840.113549.1.1.11), is not followed by a NULL as it is for every other certificate that I've looked at.  We've referred that finding to your PKI team to investigate further as it appears to be a problem with the issuing CA.

**Comment by mkorejo** [comment]
Thanks so much for following up, @tr1ck3r. I was starting to research open issues in Golang, diving back into the code, trying to figure something out myself.

**Comment by mkorejo** [comment]
I think we are clear on the problem here. Closing this issue for now. Thanks for everything!
