### ISSUE TITLE
`-key-password file:...` syntax has unexpected results with pickup command

### ISSUE THREAD

**Issue by FrazerSeymour** [Venafi/vcert#70]
**PROBLEM SUMMARY**
When using the `-key-password file:...` syntax with `vcert pickup` to fetch a key encrypted with a string from a file, vcert is encrypting the key with the path to the file not the file's contents.

**STEPS TO REPRODUCE**
1. Have a certificate in TPP where the private key is stored on the server, so it can be retrieved with `vcert pickup`.
2. In the working directory, have a text file `password.txt` with a single line containing the password you want to encrypt the certificate key with.
3. Authenticate with TPP: `vcert getcred -u $URL -username $USERNAME -password $PASSWORD`
4. Fetch the certificate with the following command: `vcert pickup -u $URL -t $TOKEN -pickup-id $PICKUP_ID -key-file domain.key -key-password file:./password.txt`
5. Verify the password of the key: `openssl rsa -in domain.key -text -noout`

**EXPECTED RESULTS**
`domain.key` file will be stored in current directory, encrypted with the password contained in the `password.txt` file in the same directory.

**ACTUAL RESULTS**
`domain.key` file is stored in current directory, encrypted with the literal string `file:./password.txt`.

**ENVIRONMENT DETAILS**
Vcert 4.6.0 for Linux, TPP v19.3.0.4463.

**COMMENTS/WORKAROUNDS**
The issue comes from [the `&& cf.format == "pkcs12"` condition in this file](https://github.com/Venafi/vcert/blob/master/cmd/vcert/passwords.go#L60). By removing that condition and compiling from source I was able to run my command above and retrieve a key encrypted with the contents of my password file.

**Comment by tr1ck3r** [comment]
Thank you for reporting this issue @FrazerSeymour.  I've added it to our internal backlog for prioritization.  We're actively working on this project so I expect we'll be able to get to it soon.
