### ISSUE TITLE
Missing documentation around non-default omit-sans command line arguments

### ISSUE THREAD

**Issue by zosocanuck** [Venafi/vcert#79]
**PROBLEM SUMMARY**
`non-default --omit-sans` are valid arguments however they are not documented via the command line help

**STEPS TO REPRODUCE**
run vcert enroll -h

**EXPECTED RESULTS**
vcert enroll -h should provide documentation around non-default and omit-sans

**ACTUAL RESULTS**
vcert enroll -h doesn't provide this documentation

**ENVIRONMENT DETAILS**
Windows 10
vCert 4.6.0

**COMMENTS/WORKAROUNDS**
None

**Comment by tr1ck3r** [comment]
@zosocanuck there currently isn't an `--omit-sans` command line parameter for the `renew` action, rather it is a proposed solution to workaround situations involving CAs with logic bugs that don't allow SANs in the request even when the SANs exactly match the SANs that the CA automatically adds when it issues the certificate (e.g. typically adding the CN and www.+CN as SANs).

Depending upon the version of TPP, the `enroll` action may provide a viable workaround for this type of situation.

**Comment by mr-tron** [comment]
https://github.com/Venafi/vcert/releases/tag/v4.9.3
