### ISSUE TITLE
Error executing vcert: exit status 2 exit status

### ISSUE THREAD

**Issue by Gl4di4torRr** [Venafi/vcert#8]
I am unable to open an issue on https://github.com/Venafi/govcert.

Currently working on building this project https://github.com/redhat-cop/cert-operator.

When I run `operator-sdk up local`, I am receiving

```2019/02/25 12:23:51 Error executing vcert: exit status 2
exit status 1
Error: failed to run operator locally: exit status 1
```

I found that the error is from this line - https://github.com/Venafi/govcert/blob/prod/embedded/client.go#L30

If I remove this case - https://github.com/redhat-cop/cert-operator/blob/master/pkg/stub/handler.go#L28
And this file - https://github.com/redhat-cop/cert-operator/blob/master/pkg/certs/venafi.go
Everything will build just fine...

I am on a Mac... This works on a Linux VM.

**Comment by tr1ck3r** [comment]
Hi @Gl4di4torRr, is there a reason you are using https://github.com/Venafi/govcert?  We've archived and no longer maintain that project because its functionality has been replaced by this project (https://github.com/Venafi/vcert).  The govcert project required a clever but rather kludgy approach of encoding the VCert CLI binaries into the source code that is not used by the vcert project.

**Comment by Gl4di4torRr** [comment]
@tr1ck3r there is a task on our backlog to upgrade to the new repo. Just wondering if anyone has noticed issues running the linux client vs the mac client. Probably the correct answer here is to update our code base to the later vcert.

**Comment by tr1ck3r** [comment]
@Gl4di4torRr no, I'm not aware of any issues on the mac but Linux was the primary target platform and govcert was based on a closed source versions of the command line utilities that are over 2 years old so it is possible.  Please let me know if you have problems with the current vcert project.  You might also want to try the current release of VCert CLI for macOS:  https://github.com/Venafi/vcert/releases/download/v3.18.3.1/VCert-macOS.zip

**Comment by Gl4di4torRr** [comment]
@tr1ck3r thanks! I am working on updating our go project now with the latest vcert. I'll just open another issue if I think there is a bug/issue.
