### ISSUE TITLE
add ca to keystore example

### ISSUE THREAD

**Issue by Gl4di4torRr** [Venafi/vcert#9]
I am following https://github.com/Venafi/vcert/blob/master/example/main.go#L37 which is setting tls to insecure. Is there an example where I take the server (venafi) certificate and place it in a keystore so I can make sure my client is making a secure call to venafi?

I am doing this in go...

**Comment by arykalin** [comment]
Hi @Gl4di4torRr, yes, we have ConnectionTrust parameter, where you can pass trust bundle pem. You can find example in our Vault PKI plugin - https://github.com/Venafi/vault-pki-backend-venafi/blob/master/plugin/pki/vcert.go#L44-L54
We will add ConnectionTrust example into vcert code soon

**Comment by Gl4di4torRr** [comment]
@arykalin worked perfectly! definitely +1 for the ssl example.

If anyone else bumps into this, I did the following.

```
trustBundle, err := ioutil.ReadFile(os.Getenv("VENAFI_CERT_PATH"))
if err != nil {
	NewCertError("trust bundle is nil")
}
trustBundlePEM := string(trustBundle)

fmt.Printf(trustBundlePEM)

var tlsTppConfig = &vcert.Config{
		ConnectorType: endpoint.ConnectorTypeTPP,
		BaseUrl:       os.Getenv("VENAFI_API_URL"),
		ConnectionTrust: trustBundlePEM,
		Credentials: &endpoint.Authentication{
			User:     os.Getenv("VENAFI_USER_NAME"),
			Password: os.Getenv("VENAFI_PASSWORD")},
		Zone: os.Getenv("VENAFI_CERT_ZONE"),
}

c, err := vcert.NewClient(tlsTppConfig)
if err != nil {
	t.Fatalf("could not connect to endpoint: %s", err)
}
```
